version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          memory: 1G

  celery-worker:
    build: 
      context: .
      args:
        - USE_GPU=true
    image: ml-api:latest
    command: bash -c 'python -m celery -A app.celery_app.celery worker --pool=solo -l INFO -Q high_priority,default,low_priority --max-tasks-per-child=50'
    environment:
      - ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=INFO
      - ENABLE_CARD_OCR=True
      - INSIGHTFACE_CTX_ID=0
      - _INSIGHTFACE_DET_SIZE=640,640
      - MAX_MEMORY_USAGE=0.9
      # CUDA and GPU specific environment variables
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_REQUIRE_CUDA=cuda>=12.8
      - TORCH_CUDA_ARCH_LIST=7.5
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
      - ONNXRUNTIME_PROVIDERS=CUDAExecutionProvider,CPUExecutionProvider
      - ONNXRUNTIME_DEVICE=cuda:0
      - ONNXRUNTIME_CUDA_DEVICE_ID=0
      - INSIGHTFACE_USE_CUDA=1
      - ONNXRUNTIME_PROVIDER_PRIORITIES=CUDAExecutionProvider,CPUExecutionProvider
      - CUDA_MODULE_LOADING=LAZY
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
    depends_on:
      redis:
        condition: service_healthy
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 28G
        reservations:
          memory: 8G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, compute]
    volumes:
      - ./ml_models:/ml_models:ro
      - ./logs:/app/logs:rw
      - model_cache:/app/temp_videos
      - insightface_models:/root/.insightface:rw
    healthcheck:
      test: celery -A app.celery_app.celery inspect ping
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: '2gb'
    restart: unless-stopped

  celery-flower:
    image: mher/flower:2.0
    command: celery flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - "5555:5555"
    environment:
      - FLOWER_BASIC_AUTH=${FLOWER_USER:-admin}:${FLOWER_PASSWORD:-admin}
    depends_on:
      - redis
      - celery-worker
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          memory: 512M

volumes:
  redis_data:
    driver: local
  model_cache:
    driver: local
  insightface_models:
    driver: local