from enum import Enum

class ErrorCode(Enum):
    """Error codes for API responses"""
    # General errors
    INTERNAL_ERROR = "INTERNAL_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    
    # Input validation errors
    INVALID_URL = "INVALID_URL"
    INVALID_IMAGE = "INVALID_IMAGE"
    INVALID_IMAGE_FORMAT = "INVALID_IMAGE_FORMAT"
    IMAGE_TOO_SMALL = "IMAGE_TOO_SMALL"
    IMAGE_TOO_LARGE = "IMAGE_TOO_LARGE"
    
    # Face detection errors
    FACE_NOT_FOUND = "FACE_NOT_FOUND"
    MULTIPLE_FACES = "MULTIPLE_FACES"
    LOW_QUALITY_FACE = "LOW_QUALITY_FACE"
    FACE_TOO_SMALL = "FACE_TOO_SMALL"
    
    # Model errors
    MODEL_NOT_LOADED = "MODEL_NOT_LOADED"
    MODEL_INFERENCE_ERROR = "MODEL_INFERENCE_ERROR"
    
    # Document specific errors
    MRZ_NOT_READABLE = "MRZ_NOT_READABLE"
    INSUFFICIENT_FEATURES = "INSUFFICIENT_FEATURES"
    LICENSE_INVALID = "LICENSE_INVALID"
    
    # Image processing errors
    IMAGE_DOWNLOAD_ERROR = "IMAGE_DOWNLOAD_ERROR"
    IMAGE_PROCESSING_ERROR = "IMAGE_PROCESSING_ERROR"
    
    # Memory/Resource errors
    INSUFFICIENT_MEMORY = "INSUFFICIENT_MEMORY"
    RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED"