version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          memory: 1G

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USE_GPU=true
    image: ml-api:latest
    command: ["./entrypoint.sh", "api"]
    environment:
      - ENV=production
      - USE_GPU=true
      - LOG_LEVEL=INFO
      - PORT=8004
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INSIGHTFACE_CTX_ID=0
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    ports:
      - "8004:8004"
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          memory: 8G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./ml_models:/ml_models:rw
      - model_cache:/app/temp_videos
      - insightface_models:/root/.insightface:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    runtime: nvidia

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USE_GPU=true
    image: ml-api:latest
    command: ["./entrypoint.sh", "celery-gpu"]
    environment:
      - ENV=production
      - USE_GPU=true
      - LOG_LEVEL=INFO
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INSIGHTFACE_CTX_ID=0
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          memory: 8G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./ml_models:/ml_models:rw
      - model_cache:/app/temp_videos
      - insightface_models:/root/.insightface:rw
    runtime: nvidia

  celery-flower:
    image: mher/flower:2.0
    command: celery flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - "5555:5555"
    environment:
      - FLOWER_BASIC_AUTH=${FLOWER_USER:-admin}:${FLOWER_PASSWORD:-admin}
    depends_on:
      - redis
      - celery-worker

volumes:
  redis_data:
  model_cache:
  insightface_models: